<a href="https://colab.research.google.com/github/stefanoridolfi/ML_Mastery_Python/blob/master/ch_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Rescale Data

In [97]:
# Chpater 7b##########################
##############################################
import pandas as pd
from pandas import set_option
from csv import reader
from matplotlib import pyplot
from matplotlib.pyplot import figure

names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
CSV_url='https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv'
dataframe=pd.read_csv(CSV_url,header=None,names=names)
print("type data",type(dataframe))
arr=dataframe.values
X=arr[:,0:8]
Y=arr[:,8]
scaler = MinMaxScaler(feature_range=(0, 1))
rescaledX = scaler.fit_transform(X)
set_printoptions(precision=3)
print("\nrescaledX prime 5 righe e prime 2 colonne\n",rescaledX[0:5,0:2])
# faccio rescale della prima colonna e la seconda colonna di X limitatte alle prima 5 righe
X1=arr[0:5,0:1]
X2=arr[0:5,1:2]
print("\nX1\n",X1)
print("\nX2\n",X2)
rescaledX1 = scaler.fit_transform(X1)
rescaledX2 = scaler.fit_transform(X2)
print("\nrescaledX1\n",rescaledX1)
print("\nrescaledX2\n",rescaledX2)
# mean using pandas
u=arr.mean(axis = 0) 
u1=X1.mean(axis=0)
sta1=X1.std(axis=0)
print("\nmedia\n",u)
sta=arr.std(axis = 0) 
print("\nstandard deviation\n",sta)

print("\nmedia X1",u1)
print("\nstandard deviation X1",sta1)


type data <class 'pandas.core.frame.DataFrame'>

rescaledX prime 5 righe e prime 2 colonne
 [[0.353 0.744]
 [0.059 0.427]
 [0.471 0.92 ]
 [0.059 0.447]
 [0.    0.688]]

X1
 [[6.]
 [1.]
 [8.]
 [1.]
 [0.]]

X2
 [[148.]
 [ 85.]
 [183.]
 [ 89.]
 [137.]]

rescaledX1
 [[0.75 ]
 [0.125]
 [1.   ]
 [0.125]
 [0.   ]]

rescaledX2
 [[0.643]
 [0.   ]
 [1.   ]
 [0.041]
 [0.531]]

media
 [  3.845 120.895  69.105  20.536  79.799  31.993   0.472  33.241   0.349]

standard deviation
 [  3.367  31.952  19.343  15.942 115.169   7.879   0.331  11.753   0.477]

media X1 [3.2]

standard deviation X1 [3.187]


Standardize features by removing the mean and scaling to unit variance

The standard score of a sample x is calculated as:

z = (x - u) / s

where u is the mean of the training samples or zero if with_mean=False, and s is the standard deviation of the training samples or one if with_std=False.

# Rescale Data description

When your data is comprised of attributes with varying scales, many machine learning algorithms can benefit from rescaling the attributes to all have the same scale. Often this is referred to as normalization and attributes are often rescaled into the range between 0 and 1. This is useful for optimization algorithms used in the core of machine learning algorithms like gradient descent. It is also useful for algorithms that weight inputs like regression and neural networks and algorithms that use distance measures like k-Nearest Neighbors. You can rescale your data using scikit-learn using the *MinMaxScaler *class.

---

MinMax Scaling

A function for min-max scaling of pandas DataFrames or NumPy arrays.

from mlxtend.preprocessing import MinMaxScaling

An alternative approach to Z-score normalization (or standardization) is the so-called Min-Max scaling (often also simply called "normalization" - a common cause for ambiguities). In this approach, the data is scaled to a fixed range - usually 0 to 1. The cost of having this bounded range - in contrast to standardization - is that we will end up with smaller standard deviations, which can suppress the effect of outliers.

A Min-Max scaling is typically done via the following equation:

Xsc=(X−Xmin)/(Xmax−Xmin)



In [0]:
# Rscale numpy array
set_printoptions(precision=3)
import numpy as np
X = np.array([[1, 10], [2, 9], [3, 8], 
              [4, 7], [5, 6], [6, 5]])
print("type(X):",type(X),"dim X:",X.shape)
print("X",X)

# Rescale pandas dataframe
#s1 e s2 sono rispettivamente la prima colonna e la seconda colonna di X limitatte alle prima 5 righe: ovvero s1=X1 s2=X2
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from mlxtend.preprocessing import minmax_scaling
from numpy import set_printoptions
d = {'s1': [6,1,8,1,0], 's2':  [148,85,183,89,137]}
df = pd.DataFrame(data=d)
print("\ndataframe\n",df)
minmax_scaling(df, columns=['s1', 's2'])

# Rescale list per dimostrare la formula di rescale: rescale di lista l1 e di lista l2. l1 ed l2 sono s1 ed s2
l1=[6,1,8,1,0]
l2= [148,85,183,89,137]
ml1=min(l1)
Ml1=max(l1)
print("Ml1",Ml1)
print("ml1",ml1)
ml2=min(l2)
Ml2=max(l2)
print("Ml2",Ml2)
print("ml2",ml2)
Mml1=Ml1-ml1
Mml2=Ml2-ml2
l1r=[]
l2r=[]
for elem in l1:
   l1r.append((elem-ml1)/Mml1)
print("l1 resc:",l1r)
for elem in l2:
   l2r.append((elem-ml2)/Mml2)
print("l2 resc:",l2r)
scaler = MinMaxScaler(feature_range=(0, 1))
rescaleddf = scaler.fit_transform(df)
print("\nrescaleddf\n",rescaleddf)

# Dimostrazione che la funzione di rescale è esattamente quella implementata nella libreria

l1r è eguale a rescaledX1, l2 è eguale a rescaledX2 ed l1r+l2r sono eguali a rescaleddf. 